import test from 'node:test';
import assert from 'node:assert/strict';
import { World, RULES, profile, cleanInput, segmentDistance2 } from '../src/simulation.js';
function duel() { const w = new World(42), a = w.add('host', { name: 'Host', faction: 'fleet' }), b = w.add('guest', { name: 'Guest', faction: 'armada' }); Object.assign(a, { x: 30, z: -12, invulnerable: 0, cooldown: 0 }); Object.assign(b, { x: 30, z: 12, invulnerable: 0 }); return { w, a, b }; }
test('profile is bounded and faction is an allowlist', () => { const p = profile({ name: '<pilot>' + 'x'.repeat(100), faction: 'unknown' }); assert.equal(p.name.length, 16); assert.ok(!p.name.includes('<')); assert.equal(p.faction, 'fleet'); });
test('non-finite or excessive input cannot poison the simulation', () => { const i = cleanInput({ x: Infinity, z: 99, ax: NaN, az: -5, fire: 'yes', pulse: -10 }); assert.deepEqual(i, { x: 0, z: 1, ax: 0, az: -1, fire: false, boost: false, pulse: 0 }); });
test('identical seeds and ticks produce identical worlds', () => { const a = new World(917), b = new World(917); a.add('host', {}); b.add('host', {}); a.bots(6); b.bots(6); for (let i = 0; i < 900; i++) { a.tick(); b.tick(); } assert.deepEqual(a.snapshot(), b.snapshot()); });
test('diagonal input does not increase maximum speed', () => { const { w, a } = duel(); for (let i = 0; i < 50; i++) { w.setInput('host', { x: 1, z: 1 }); w.tick(); } assert.ok(Math.hypot(a.vx, a.vz) <= 26.001); });
test('segment collision catches projectiles crossing a ship between frames', () => { assert.equal(segmentDistance2(5, 0, 0, 0, 10, 0), 0); assert.equal(segmentDistance2(5, 2, 0, 0, 10, 0), 4); });
test('actual fired projectiles damage and destroy the opposing ship', () => { const { w, a, b } = duel(); for (let i = 0; i < 95; i++) { w.setInput('host', { ax: 0, az: 1, fire: true }); w.tick(); } assert.equal(w.score.fleet, 1); assert.equal(a.kills, 1); assert.equal(b.hp, 0); assert.ok(b.respawn > 0); });
test('friendly fire is disabled', () => { const { w, b } = duel(); b.faction = 'fleet'; for (let i = 0; i < 120; i++) { w.setInput('host', { ax: 0, az: 1, fire: true }); w.tick(); } assert.equal(b.hp, 100); assert.equal(w.score.fleet, 0); });
test('a destroyed pilot respawns once with full hull and grace time', () => { const { w, a, b } = duel(); w.hurt(b, 100, a); for (let i = 0; i < 155; i++) w.tick(); assert.equal(b.hp, 100); assert.equal(b.deaths, 1); assert.equal(b.respawn, 0); assert.ok(b.invulnerable > 0); });
test('one pulse sequence is consumed only once', () => { const { w, a, b } = duel(); b.z = -3; for (let i = 0; i < 400; i++) { w.setInput('host', { pulse: 1 }); w.tick(); } assert.equal(b.hp, 68); assert.equal(a.lastPulse, 1); assert.equal(w.events.filter(e => e.type === 'pulse').length, 1); });
test('stale remote input stops firing and movement', () => { const { w, a } = duel(); w.setInput('host', { x: 1, fire: true }); for (let i = 0; i < 120; i++) w.tick(); assert.ok(Math.abs(a.vx) < 0.01); assert.ok(w.events.filter(e => e.type === 'shot').length <= 2); });
test('arena and core constraints cannot produce NaN positions', () => { const { w, a } = duel(); a.x = a.z = 0; w.tick(); assert.ok(Number.isFinite(a.x)); assert.ok(Math.hypot(a.x, a.z) >= RULES.core + 3); a.x = 1000; w.tick(); assert.ok(Math.hypot(a.x, a.z) <= RULES.radius - 3 + 0.0001); });
test('ship count is bounded', () => { const w = new World(); w.bots(1000); assert.equal(w.ships.size, RULES.ships); });
test('score threshold ends the match and freezes the clock', () => { const { w } = duel(); w.score.armada = RULES.target; w.tick(); assert.equal(w.winner, 'armada'); const t = w.time; w.tick(); assert.equal(w.time, t); });
test('time limit resolves a tied match', () => { const w = new World(); w.time = RULES.duration - 0.001; w.tick(); assert.equal(w.winner, 'draw'); });
test('snapshots are JSON serializable and contain no Map or renderer objects', () => { const { w } = duel(); const s = JSON.parse(JSON.stringify(w.snapshot())); assert.equal(s.ships.length, 2); assert.equal(s.ships[0].id, 'host'); assert.ok(!('input' in s.ships[0])); });
